name: examples-next-app
services:
  deps:
    image: imbios/bun-node:latest
    working_dir: /app
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
    command: bun install
    networks:
      - default

  next-app:
    image: imbios/bun-node:latest
    working_dir: /app
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
    depends_on:
      deps:
        condition: service_completed_successfully
    command: bun run dev -- -p 3000 -H 0.0.0.0
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    labels:
      caddy: examples-next-app.hack
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.tls: internal
    networks:
      - hack-dev
      - default
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example-db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default
  redis:
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - redis-data:/bitnami/redis/data
    networks:
      - default
  ops:
    image: imbios/bun-node:latest
    working_dir: /app
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/example-db
    depends_on:
      - db
      - deps
    networks:
      - default
    profiles: ["ops"]
    command: bun run db:generate
networks:
  hack-dev:
    external: true

volumes:
  postgres-data:
  node_modules: